version: '3.9'
services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.64@sha256:11ba8ff3870e8ee88494ad5b34e6942d1d91321483895c05aa264643f6d99a94
    hostname: rustfs
    container_name: rustfs__rustfs
    restart: unless-stopped

    environment:
      - RUSTFS_ACCESS_KEY=root
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}

    volumes:
      - type: bind
        source: /data/rustfs/data
        target: /data

      - type: bind
        source: /data/rustfs/logs
        target: /logs

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 8192m

  cloudflared:
    image: cloudflare/cloudflared:2025.11.1-amd64@sha256:f751174c3d8ae54b12575af320a4aa01bb3b6e61ab82aa1e4f8ecac8a079ce61
    hostname: cloudflared
    container_name: rustfs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 4096m

networks:
  default:
    name: rustfs__default
