version: '3.9'
services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.78@sha256:888058cdf07939d1bae56235a07ac96354db8cae948aa38ba818919a4039923f
    hostname: rustfs
    container_name: rustfs__rustfs
    restart: unless-stopped

    environment:
      - RUSTFS_ACCESS_KEY=root
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}

    volumes:
      - type: bind
        source: /data/rustfs/data
        target: /data

      - type: bind
        source: /data/rustfs/logs
        target: /logs

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 8192m

  cloudflared:
    image: cloudflare/cloudflared:2025.10.0-amd64@sha256:de377b1bb1cb9298fe7153171bc60180e5cda167dc14217d82860571e6053530
    hostname: cloudflared
    container_name: rustfs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 4096m

networks:
  default:
    name: rustfs__default
